name: Deploy to Xserver

on:
  push:
    branches: [main]
  workflow_dispatch: # Web UI から手動実行用

concurrency:
  group: deploy-to-xserver
  cancel-in-progress: false # キャンセルせず「待ち行列」にする

jobs:
  deploy-to-xserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        env:
          MICROCMS_SERVICE_DOMAIN: ${{ secrets.MICROCMS_SERVICE_DOMAIN }}
          MICROCMS_API_KEY: ${{ secrets.MICROCMS_API_KEY }}
        run: pnpm build

      # SSH 準備
      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      # rsync デプロイ
      - name: Deploy to Xserver
        env:
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          REMOTE_DIR: ${{ secrets.SSH_PROD_REMOTE_DIR }}
        run: |
          LOCAL_DIR=./_dist/

          rsync -azv --delete --itemize-changes \
            --exclude='/.user.ini' \
            --exclude='/.htaccess' \
            -e "ssh -p ${REMOTE_PORT} -i ~/.ssh/id_rsa -o StrictHostKeyChecking=yes" \
            "${LOCAL_DIR}" \
            "${REMOTE_USER}@${REMOTE_HOST}:${REMOTE_DIR}"
